logging.file: logs/app-test.log
logging.level.com.example.webDemo: debug

spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/security_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username: root
spring.datasource.password: 123456

logging.level.org.springframework.security: info
spring.thymeleaf.cache: false
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

server:
  port: 8080
  session:
    timeout: 86400
spring:
  datasource:
    initialize: false